### ISSUE TITLE
Unique Identifier for Donors

### ISSUE THREAD

**Issue by ssfcultra** [DonorDrive/PublicAPI#12]
We have found that it is very hard to distinguish a unique donor. Would it be possible to add a field onto the Dontation API that would be a uniquely identifying field so I could tell that a donation came from a unique donor?

Our group runs a 24-hour raffle with limits on how many prizes a donor can win by tier. This is the impetus for asking for a unique donor id. Currently using DonorName isn't unique enough for our purposes.

**Comment by timmixell** [comment]
Definitely something we'll consider for our next round of improvements!

**Comment by Zosoled** [comment]
Email address is often used for this purpose.

**Comment by ssfcultra** [comment]
I would recommend not using email address as it could be considered personally identifiable information. Additionally, it could open up groups to potentially having to be GDPR compliant.

**Comment by timmixell** [comment]
the `donorID` value furnished by the API will be distinct for each donor that selected public name/message visibility at the time of the donation. individual donations are now identified with the `donationID`

https://github.com/DonorDrive/PublicAPI/blob/master/docs/1.0/resources/donations.md
