### ISSUE TITLE
Custom Fields in API

### ISSUE THREAD

**Issue by jdozierezell** [DonorDrive/PublicAPI#15]
Are custom fields exposed in the public API? I need access to them in order to filter a response correctly.

**Comment by timmixell** [comment]
Can you please elaborate on which fields you are trying to access?

Currently, the only fields exposed are those in the documentation of this repository.

Thanks!

**Comment by jdozierezell** [comment]
Sure. My company currently uses a custom field called `customfieldcode1` to pass information about the category of event (separate from type) that I need access to in order to allow users to filter by that category. Similar to how I can query with http://afsp.donordrive.com/api/events?where=province%3DAL, I'd love to be able to do http://afsp.donordrive.com/api/events?where=customcode1%3DCT or something else along those lines. If this isn't possible, how would you recommend getting that information?

Also I know this isn't an issue per se, so if there's a better customer support location where I should ask these questions, feel free to point me there. Thanks!

**Comment by timmixell** [comment]
I understand. This would be something you'd need to work with your contact at AFSP on. We have other interfaces tailored for B2B use that may better suit your requirements.
