### ISSUE TITLE
API endpoints for superteams?

### ISSUE THREAD

**Issue by MoeFwacky** [DonorDrive/PublicAPI#17]
I'm looking for, and can't seem to find, any API endpoints for superteam data. For reference a superteam is a team that can have both participants and other teams contributing towards a total goal ([example here](https://www.extra-life.org/index.cfm?fuseaction=cms.page&id=1492)).

What I'm looking to do is grab the donation total and goal numbers from the superteam without having to aggregate all of the subteams and add up the total "manually."

**Comment by timmixell** [comment]
@MoeFwacky we're going to shoot for API parity with what we're doing behind the scenes right now in the product. This would cover cumulative total raised/overall goal, as well as the number of participants and teams.

**Comment by timmixell** [comment]
this is live
