### ISSUE TITLE
Completed Boolean on Milestone API Endpoint

### ISSUE THREAD

**Issue by jsstudz** [DonorDrive/PublicAPI#21]
Looking at the [Milestone metadata](https://github.com/DonorDrive/PublicAPI/blob/master/docs/1.0/resources/milestones.md) it would be nice to be able to have something (possibly a bool) that the milestone was reached. Comparing the milestone fundraising goal to the total raised by the participant. 

This would make it easier to work with rather than pulling participants information as well as milestone information. 

Milestone.Completed = Milestone.FundraisingGoal <= Participants.SumDonations 

Thank you

**Comment by timmixell** [comment]
this is live
