### ISSUE TITLE
Include `sumPledges` in teams endpoints

### ISSUE THREAD

**Issue by timmixell** [DonorDrive/PublicAPI#26]
`sumPledges` is offered as a field inside the `/participants` endpoints. It would be nice for this field to be accessible from `/teams` endpoints as well.

**Comment by morleym** [comment]
+1, I'm not seeing a way to get your total as a team like you'd see on a team page. I would expect this functionality to be available.

**Comment by timmixell** [comment]
resolved w/ #32

**Comment by timmixell** [comment]
@morleym apologies for not following up sooner. this functionality is actually available right now, provided that pledges are enabled in the instance of DonorDrive you're working with. take a look and let me know if you run into any issues. thanks!

**Comment by morleym** [comment]
@timmixell i took a closer look through things, and I realized that the event I'm working with isn't using teams. So I latched onto this issue incorrectly.

I have opened a separate issue for my ask: #35
