### ISSUE TITLE
Retrieve the donations sum, and target, shown on event page

### ISSUE THREAD

**Issue by morleym** [DonorDrive/PublicAPI#35]
I am looking at an event: https://lanfest.donordrive.com/index.cfm?fuseaction=donorDrive.event&eventID=510

The event page displays a target and a current value:

![image](https://user-images.githubusercontent.com/31675433/78827601-33d7ec00-7998-11ea-84b5-682fc24e7dd5.png)

The public API for the event only returns the following:

```json
{
    "endDateUTC": "2020-04-14T02:00:00.0+0000",
    "eventID": 510,
    "timezone": "America/New_York",
    "type": "P",
    "startDateUTC": "2020-04-10T22:00:00.0+0000",
    "name": "Corona Clash"
}
```

I did not see a means in API documentation to retrieve either the target ($5000 in the image) or the current ($90 in the image) so I am filing this issue to request that functionality. This event does not have any teams.

**Comment by morleym** [comment]
More context: the use case is to display this target and sum in custom layouts either for a website or a broadcast.

**Comment by timmixell** [comment]
@morleym , confirming you're looking to get fundraising info in the `/api/events` and/or `/api/events/EVENT-ID` endpoints. if so, we're working on it!

**Comment by morleym** [comment]
@timmixell that is correct. In this example, I'd like to `GET https://lanfest.donordrive.com/api/events/510` and have it return the values for the goal (5000) and current total raised (90) in some form

**Comment by WireJunky42** [comment]
Just out of curiosity, why not use the Participants endpoint as it already returns the goal and sum donations?  This is what I am using to create a progress tracker.
``` JSON
   {
    "displayName": "Liam Bonham",
    "fundraisingGoal": 8000,
    "eventName": "Test Participant Event",
    "links": {
      "donate": "https://try.donordrive.com/index.cfm?fuseaction=donordrive.participant&participantID=19265#donate",
      "page": "https://try.donordrive.com/index.cfm?fuseaction=donordrive.participant&participantID=19265"
    },
    "createdDateUTC": "2019-11-02T15:02:38.93+0000",
    "eventID": 508,
    "sumDonations": 4661,
    "participantID": 19265,
    "teamName": "The Bonhams",
    "avatarImageURL": "//static.donordrive.com/clients/try/img/avatar-constituent-default.gif",
    "teamID": 8775,
    "isTeamCaptain": true,
    "sumPledges": 0,
    "numDonations": 51
  },

**Comment by timmixell** [comment]
@morleym please see the updates in https://github.com/DonorDrive/PublicAPI/pull/40. The actual API changes are live, the PR reflects the updated behavior. Note that goal and total raised are only returned if they've been made visible by an administrator.
