### ISSUE TITLE
isComplete not returned on Milestones request

### ISSUE THREAD

**Issue by jsstudz** [DonorDrive/PublicAPI#36]
![milestones](https://user-images.githubusercontent.com/36231239/80047112-2a8b6b00-84d2-11ea-8831-e7c9e50f02b9.png)

To Reproduce: 
Visit my request : https://www.extra-life.org/api/participants/400560/milestones

The request is not pulling isComplete when called. 

Also, is it possible to make it filterable on request as well?

**Comment by jsstudz** [comment]
After further investigation, maybe it only shows for ones that are complete, rather than showing false for ones that aren't complete?

**Comment by timmixell** [comment]
That is correct, though I did see a subtle issue in the documentation for milestones. Will update soon.

**Comment by timmixell** [comment]
@jsstudz please note that the `isComplete` flag is marked as "optional" in the table: https://github.com/DonorDrive/PublicAPI/blob/master/docs/1.1/resources/milestones.md

That being said, I'm open to suggestions to make the formatting more apparent.
