### ISSUE TITLE
Ability to view past Incentives

### ISSUE THREAD

**Issue by jsstudz** [DonorDrive/PublicAPI#41]
It would be nice to have the ability to view Incentives that have passed their End Date. Gives the ability to track statistically which incentives are working and which incentives are not working. Also, from a list perspective, when viewing past donations you can associate that donation to incentive. Sometimes a few of us don't get around to redeeming incentives til past their end date.

Currently, /incentives only shows active incentives right now.

**Comment by timmixell** [comment]
@jsstudz this should be [available for you now](https://github.com/DonorDrive/PublicAPI/blob/1.3/resources/incentives.md). note: the addition of the `isActive` field that you can filter on to control what incentives to display
