### ISSUE TITLE
API Endpoints Inaccessible via App

### ISSUE THREAD

**Issue by djotaku** [DonorDrive/PublicAPI#48]
Many complaints on Discord, so it's not just my App. Endpoints accessible via website.

I'm getting a 403: Forbidden Error

**Comment by ndtex** [comment]
Image of issue when I run my code:

![image](https://user-images.githubusercontent.com/51942036/126153147-8876ae01-5a67-4286-8305-c7f4135c941e.png)

Relevant code for the above (using Node JS)

`const basicInfo = 'https://www.extra-life.org/api/participants/' + config.participantID
console.log("Attempting to use: " + basicInfo)

...

function updateGoal() {
    request({
        url: basicInfo,
        json: true
    }, (error, response, body) => {
        if (error || response.statusCode !== 200) {
            console.log(`Error in updateGoal(): ${error} (status code ${response.statusCode})`)
            return
        }

...

updateGoal()
setInterval(updateGoal, 70000)`

**Comment by djotaku** [comment]
Working for me today, did you guys at DonorDrive change anything?

**Comment by Maeglin73** [comment]
They changed the Cloudflare firewall rules again, and it seems to be working here, too. I was waiting a bit to test it, based on Havok's comment in the Discord about the change rollout taking some time.

**Comment by timmixell** [comment]
we are working on ways to make this a better experience moving forward. in the meantime, don't hesitate to reach out here, or via the #donordrive-support channel on Extra Life's Discord server if this pops up again
