### ISSUE TITLE
All endpoints appear to be returning 404's

### ISSUE THREAD

**Issue by 123Spork** [DonorDrive/PublicAPI#62]
Using the example API in the documentation, doing a GET to `https://try.donordrive.com/api/event` (and all other available API endpoints) appear to be returning 404 not found errors.

Has the domain name changed for the public API?

**Comment by timmixell** [comment]
greetings @123Spork , double check the [docs](https://github.com/DonorDrive/PublicAPI/blob/master/resources/events.md) - we don't currently surface lists of events through the Public API. you _can_ get to specific events, via the ID: https://try.donordrive.com/api/events/500

**Comment by ItsJustAGitHubMichealWhosGonnaSeeIt5Ppl** [comment]
Hi I don't think this is resolved.  I cannot get results for our team using our ID
"https://try.donordrive.com/api/teams/[teamID]
