### ISSUE TITLE
Feature Request: Get Participant Stream

### ISSUE THREAD

**Issue by alex-lyons-pariveda** [DonorDrive/PublicAPI#7]
Would it be possible to return the stream of a given participant? I am now able to add my stream to my donation page, and it would be great to get a list of all of the streams that my team members are using. I am working on a site to showcase all of the team, somewhat simultaneously, and this would be a great feature.

**Comment by timmixell** [comment]
this is resolved with the new `links.stream` property: https://github.com/DonorDrive/PublicAPI/blob/master/docs/1.0/resources/participants.md
